UPDATE `TaskList` SET `module` = 'INTERNAL_AFFAIRS' WHERE `module` = 'DETECTIVE';
UPDATE `SruFolder` SET `module` = 'INTERNAL_AFFAIRS' WHERE `module` = 'DETECTIVE';
UPDATE `SruDocument` SET `module` = 'INTERNAL_AFFAIRS' WHERE `module` = 'DETECTIVE';
UPDATE `CalendarEvent` SET `module` = 'INTERNAL_AFFAIRS' WHERE `module` = 'DETECTIVE';
UPDATE `CalendarEvent` SET `type` = 'INTERNAL_AFFAIRS_BRIEFING' WHERE `type` = 'DETECTIVE_BRIEFING';
UPDATE `CalendarEvent` SET `type` = 'INTERNAL_AFFAIRS_CASE' WHERE `type` = 'DETECTIVE_CASE';

ALTER TABLE `Officer` DROP INDEX `Officer_badgeNumber_key`;
CREATE INDEX `Officer_badgeNumber_idx` ON `Officer`(`badgeNumber`);

ALTER TABLE `TaskList`
  MODIFY `module` ENUM('ACADEMY', 'HR', 'SRU', 'DETECTIVE', 'INTERNAL_AFFAIRS', 'AIR_SUPPORT') NOT NULL;
ALTER TABLE `SruFolder`
  MODIFY `module` ENUM('ACADEMY', 'HR', 'SRU', 'DETECTIVE', 'INTERNAL_AFFAIRS', 'AIR_SUPPORT') NOT NULL DEFAULT 'SRU';
ALTER TABLE `SruDocument`
  MODIFY `module` ENUM('ACADEMY', 'HR', 'SRU', 'DETECTIVE', 'INTERNAL_AFFAIRS', 'AIR_SUPPORT') NOT NULL DEFAULT 'SRU';
ALTER TABLE `CalendarEvent`
  MODIFY `module` ENUM('ACADEMY', 'HR', 'SRU', 'DETECTIVE', 'INTERNAL_AFFAIRS', 'AIR_SUPPORT') NULL,
  MODIFY `type` ENUM('TRAINING', 'MEETING', 'ACADEMY', 'EXAM', 'HR_DEADLINE', 'SRU_TRAINING', 'SRU_OPERATION', 'DETECTIVE_BRIEFING', 'DETECTIVE_CASE', 'INTERNAL_AFFAIRS_BRIEFING', 'INTERNAL_AFFAIRS_CASE', 'AIR_SUPPORT_TRAINING', 'AIR_SUPPORT_OPERATION', 'OTHER') NOT NULL DEFAULT 'OTHER';
